services:
  backend:
    build: ./acre-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ./acre-backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build: ./acre-ui
    ports:
      - "5173:5173"
    depends_on:
      - backend